# Generated by Django 4.1.5 on 2023-06-02 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='note',
            field=models.TextField(default='none'),
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
