# Generated by Django 4.1.5 on 2023-06-02 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_note_delete_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='note',
            field=models.TextField(max_length=256),
        ),
    ]
