# Generated by Django 4.1.5 on 2023-06-03 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_sale_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='note',
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=256)),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='note', to='sales.sale')),
            ],
            options={
                'db_table': 'Notes',
            },
        ),
    ]
