# Generated by Django 4.1.5 on 2023-06-03 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_remove_note_content_remove_note_sale_note_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.note'),
        ),
    ]
