# Generated by Django 4.1.5 on 2023-06-05 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_remove_sale_note_sale_allergies_delete_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='allergies',
            new_name='note',
        ),
    ]
