# Generated by Django 4.1.5 on 2023-05-31 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_allergies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='allergies',
            field=models.TextField(max_length=256),
        ),
    ]
